### ISSUE TITLE
repo url to https

### ISSUE THREAD

**Issue by 304NotModified** [nunit/nunit3-tdnet-adapter#15]
Please change the url of the repo to https :)

![image](https://user-images.githubusercontent.com/5808377/52538179-c7e7fc80-2d6f-11e9-919a-667a865ddc07.png)

It should be https://testdriven.net

related: https://github.com/nunit/nunit/issues/3161

**Comment by 304NotModified** [comment]
bump @ChrisMaddock

**Comment by jcansdale** [comment]
Done. 👍
